class CreateGamerooms < ActiveRecord::Migration[5.2]
  def change
    create_table :gamerooms do |t|
      t.references :user, foreign_key: true
      t.references :card, foreign_key: true
      t.string :p1
      t.string :p2
      t.string :player1Key
      t.string :player2Key
      t.string :turn
      t.integer :room
      t.string :key
      t.string :p1_hand_1
      t.string :p1_hand_2
      t.string :p1_hand_3
      t.string :p1_hand_4
      t.string :p1_hand_5
      t.string :p1_hand_6
      t.string :p1_hand_7
      t.string :p2_hand_1
      t.string :p2_hand_2
      t.string :p2_hand_3
      t.string :p2_hand_4
      t.string :p2_hand_5
      t.string :p2_hand_6
      t.string :p2_hand_7
      t.string :p1Monster1
      t.string :p1Monster2
      t.string :p1Monster3
      t.string :p1Monster4
      t.string :p1Monster5
      t.string :p1Magic1
      t.string :p1Magic2
      t.string :p1Magic3
      t.string :p1Magic4
      t.string :p1Magic5
      t.string :p2Monster1
      t.string :p2Monster2
      t.string :p2Monster3
      t.string :p2Monster4
      t.string :p2Monster5
      t.string :p2Magic1
      t.string :p2Magic2
      t.string :p2Magic3
      t.string :p2Magic4
      t.string :p2Magic5
      t.string :p1_deck_1
      t.string :p1_deck_2
      t.string :p1_deck_3
      t.string :p1_deck_4
      t.string :p1_deck_5
      t.string :p1_deck_6
      t.string :p1_deck_7
      t.string :p1_deck_8
      t.string :p1_deck_9
      t.string :p1_deck_10
      t.string :p1_deck_11
      t.string :p1_deck_12
      t.string :p1_deck_13
      t.string :p1_deck_14
      t.string :p1_deck_15
      t.string :p1_deck_16
      t.string :p1_deck_17
      t.string :p1_deck_18
      t.string :p1_deck_19
      t.string :p1_deck_20
      t.string :p1_deck_21
      t.string :p1_deck_22
      t.string :p1_deck_23
      t.string :p1_deck_24
      t.string :p1_deck_25
      t.string :p1_deck_26
      t.string :p1_deck_27
      t.string :p1_deck_28
      t.string :p1_deck_29
      t.string :p1_deck_30
      t.string :p1_deck_31
      t.string :p1_deck_32
      t.string :p1_deck_33
      t.string :p1_deck_34
      t.string :p1_deck_35
      t.string :p1_deck_36
      t.string :p1_deck_37
      t.string :p1_deck_38
      t.string :p1_deck_39
      t.string :p1_deck_40
      t.string :p2_deck_1
      t.string :p2_deck_2
      t.string :p2_deck_3
      t.string :p2_deck_4
      t.string :p2_deck_5
      t.string :p2_deck_6
      t.string :p2_deck_7
      t.string :p2_deck_8
      t.string :p2_deck_9
      t.string :p2_deck_10
      t.string :p2_deck_11
      t.string :p2_deck_12
      t.string :p2_deck_13
      t.string :p2_deck_14
      t.string :p2_deck_15
      t.string :p2_deck_16
      t.string :p2_deck_17
      t.string :p2_deck_18
      t.string :p2_deck_19
      t.string :p2_deck_20
      t.string :p2_deck_21
      t.string :p2_deck_22
      t.string :p2_deck_23
      t.string :p2_deck_24
      t.string :p2_deck_25
      t.string :p2_deck_26
      t.string :p2_deck_27
      t.string :p2_deck_28
      t.string :p2_deck_29
      t.string :p2_deck_30
      t.string :p2_deck_31
      t.string :p2_deck_32
      t.string :p2_deck_33
      t.string :p2_deck_34
      t.string :p2_deck_35
      t.string :p2_deck_36
      t.string :p2_deck_37
      t.string :p2_deck_38
      t.string :p2_deck_39
      t.string :p2_deck_40
      t.integer :p1_life_points
      t.integer :p2_life_points

      t.timestamps
    end
  end
end
